language: java
env:
  matrix:
  - NODE_VERSION="12.13.1"
  global:
  - secure: gBFW0p04y3kmY/EJ6f3FbhMI369bYBkhoaqnfX0NPyiu3qCm0P6NpBgBX24ypVJ+bD5ed44mecukqpbv9ailRpVdckSgL4jcRDUyMZPSb3S/+Cvh28fEFnFd0feIuoMLNHDUKxhsLtrIG6wC0oP46SsS6NM8W4fYTb5cDg/YkaZpMwmIBtobyqnKRswMHJ2MXap1iIVQmIG9kMXDk1GZw5FMfwUvj4DS2tNG3GJtbsPe0g52WpesexQuidDFyKAn5qCP132cP2hNvUPk92/EcrxY0AWcfvUji+d5+NWS3HtxSaulktB38WKjs9u7x65r5bM8D0Dg9yxszbMQsxfZJbdaYkGVm0CdD0EcDYznZugW6SzED+STocy5QlPrYctgR0x7wsRwHqif0GqiWR6HGAI+5gP5th4Z7a9kvCtA87tJSsHvxG52sWVvsswqkQYwn3pUQfvausiYNOkYpoArWQMAzNGvNJdxS66C0NnXTm5KQA/btdHziPW/5zBQN8bxCkYyPS/5aRcQa5oPQcTg+QN4sGBddiUGjbdXxyACN+NjhmtSOQl6LEcYCQcz2VOmUvHInaDCcB7ToegzDkSihproZzyQkSPIEAuvizbWJdSOFIj91UOYeQjA0RHClEqBhd+MnMT75RGPNZLc2aZDo1wIQk4aA071e01kh9Tsj3c=
  - secure: F57lWeuXZY6w1KOnlfdUi9BKFQMybkHJPSyvq6RCEoiaUcuqsfAHMNdV5xmAgdMcm3NhGgtFx1YBhdjB8pI1oZIHeGFXV7qz7ovp84WQdsq+1tLsEctBtiey6ZULvxwLozx9XA34zoeC6kAA/uyCIyb8Ru+n2+AiCIKikhzq20pPzKX4//kpSscEHz7ylisQy8afeSDufwhAo73z/XUjj7rDIIMv4vm9IBl/W0+RSybW5RAXYNdlEuhdzue15LfdNo67wfTvxVriCwDiRenyMucLCufGmsDOZKWzxnNl/kkajqrttXPqvAE+kvYzNHMshh+RRKTZM43h1CMMDcsI9Ct+PPXKX9OfR8HYPz7dGgRzpDS37HvkYjG8XIcOyWl7OxjfDbbB6nugo2VzL+FGzd2SbMPf2NiiexQFOYFdHza4du6xJo1QpnC5T0U+LlD4dx/G46T93xySwnW/T7CG7BykojFr/xkA0Hr66hG9Wx6fnxkBlyTAv/JH6ynN23hGS/1G5HkkPDSrKpawyWtJC2CGTcUXRtOl35mVOOxyelHyIDHoCyYTmcf/+WGKuxXyMhJZ2vG2TG7b+8vsU1mFGCsLw95tUHUPyLEubUPctTAQKSCIZeaAj8L8PoQ9zH9V8xYO8ivZyGzU/MM0qVNxBB2xH6oRThRsf5RPha3vXHg=
services:
- docker
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - node_modules
jobs:
  include:
  - stage: Prepare
    script:
    - nvm install $NODE_VERSION
    - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - stage: Build
    script:
    - mvn install -Ppackage-docker-image
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag unige/api-gateway marktropin/api-gateway:latest
    - docker tag unige/regulatory-service marktropin/regulatory-service:latest
    - docker tag unige/valuation-service marktropin/valuation-service:latest
    - docker tag unige/instrument-service marktropin/instrument-service:latest
    - docker tag unige/counterparty-service marktropin/counterparty-service:latest
    - docker push marktropin/api-gateway:latest
    - docker push marktropin/regulatory-service:latest
    - docker push marktropin/valuation-service:latest
    - docker push marktropin/instrument-service:latest
    - docker push marktropin/counterparty-service:latest
    - mvn sonar:sonar -Dsonar.projectKey=PInfo-2 -Dsonar.organization=Group2Project
      -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=68db16192c9f0533a0926c86cf71c30b2331c97c
  - stage: Build
    script:
    - cd web-ui
    - pwd
    - npm -v
    - npm install
    - npm update
    - npm run-script build --prod
    - docker build -t unige/web-ui .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag unige/web-ui marktropin/web-ui:latest
    - docker push marktropin/web-ui:latest
addons:
  sonarcloud:
    organization: pinfo-2020
    token:
		secure: "W9jtjH7IBt0uvMwjL+B63Zw0dEgAMFn6sbo9fjUksgRKSW/IFvRgHk3YtFITnoy6NxG9ytPmPgQtllQEZVCjNsw9xkXpgVZucttiTrdM31bkMFAsyTKjpbix5ddRbLGjl9LewkuHtqJEKex8jRUnZ9tNIrxHhWgCdAiecJhKv5Zt94rfiYwqcXCkEjUWO0dgDVcxk5nQzYpthhpZ1TqgyUxLa3NBJEq8wOZL9/tB3yhLDrfp9/+SP/tV8czbPw+Pn78kHJu5SMs4U7EGZ5bXGKeRujMYtpg+b/6OzQYOqOxB/evyReRkvP3sXGJ4na16MssRS+jBbT7qAibNjPB54Xq3rBq1VZPSDVl8gT5Lr0eJTuxmz/cc0JvpZgE+Owp3c7brLauLL8jQT3NeVXqXc8bkPM13qA36G6Uc4WN+ex9bl6zKI8NA7R4xBaKS1yWmjTAXMM4iaVrWLERXw6cms8Ig1zImbxR9MvXQkaSQS6Tgrf1N7wfiejVXAzLLl4wXq9pcJisktI1dbis84IkuC6RAUbq+Y2VUo/ciJRrQJ4aP16oTi8z7ZlXd6iee/AnUdn0+OwV9QTZhRY+W3uG4Tf87EEqZ6qeUjoTi9Rw99td0rVNuwEnZYoQDmpIjh7mFazdiJn3IFtGgpyoisWJlAmWiWdVZemxwkTjZxc4xNyw="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-2
