language: java

# Set current branch to MASTER
branches:
  only:
    - master

# Don't use the Maven default command
install: /bin/true

env:
  matrix:
  - NODE_VERSION="12.13.1"
  global:
  - TRAVIS_SECURE_ENV_VARS: true
  - secure: gBFW0p04y3kmY/EJ6f3FbhMI369bYBkhoaqnfX0NPyiu3qCm0P6NpBgBX24ypVJ+bD5ed44mecukqpbv9ailRpVdckSgL4jcRDUyMZPSb3S/+Cvh28fEFnFd0feIuoMLNHDUKxhsLtrIG6wC0oP46SsS6NM8W4fYTb5cDg/YkaZpMwmIBtobyqnKRswMHJ2MXap1iIVQmIG9kMXDk1GZw5FMfwUvj4DS2tNG3GJtbsPe0g52WpesexQuidDFyKAn5qCP132cP2hNvUPk92/EcrxY0AWcfvUji+d5+NWS3HtxSaulktB38WKjs9u7x65r5bM8D0Dg9yxszbMQsxfZJbdaYkGVm0CdD0EcDYznZugW6SzED+STocy5QlPrYctgR0x7wsRwHqif0GqiWR6HGAI+5gP5th4Z7a9kvCtA87tJSsHvxG52sWVvsswqkQYwn3pUQfvausiYNOkYpoArWQMAzNGvNJdxS66C0NnXTm5KQA/btdHziPW/5zBQN8bxCkYyPS/5aRcQa5oPQcTg+QN4sGBddiUGjbdXxyACN+NjhmtSOQl6LEcYCQcz2VOmUvHInaDCcB7ToegzDkSihproZzyQkSPIEAuvizbWJdSOFIj91UOYeQjA0RHClEqBhd+MnMT75RGPNZLc2aZDo1wIQk4aA071e01kh9Tsj3c=
  - secure: F57lWeuXZY6w1KOnlfdUi9BKFQMybkHJPSyvq6RCEoiaUcuqsfAHMNdV5xmAgdMcm3NhGgtFx1YBhdjB8pI1oZIHeGFXV7qz7ovp84WQdsq+1tLsEctBtiey6ZULvxwLozx9XA34zoeC6kAA/uyCIyb8Ru+n2+AiCIKikhzq20pPzKX4//kpSscEHz7ylisQy8afeSDufwhAo73z/XUjj7rDIIMv4vm9IBl/W0+RSybW5RAXYNdlEuhdzue15LfdNo67wfTvxVriCwDiRenyMucLCufGmsDOZKWzxnNl/kkajqrttXPqvAE+kvYzNHMshh+RRKTZM43h1CMMDcsI9Ct+PPXKX9OfR8HYPz7dGgRzpDS37HvkYjG8XIcOyWl7OxjfDbbB6nugo2VzL+FGzd2SbMPf2NiiexQFOYFdHza4du6xJo1QpnC5T0U+LlD4dx/G46T93xySwnW/T7CG7BykojFr/xkA0Hr66hG9Wx6fnxkBlyTAv/JH6ynN23hGS/1G5HkkPDSrKpawyWtJC2CGTcUXRtOl35mVOOxyelHyIDHoCyYTmcf/+WGKuxXyMhJZ2vG2TG7b+8vsU1mFGCsLw95tUHUPyLEubUPctTAQKSCIZeaAj8L8PoQ9zH9V8xYO8ivZyGzU/MM0qVNxBB2xH6oRThRsf5RPha3vXHg=

services:
- docker

cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - node_modules

jobs:
  include:
  - stage: Prepare
    script:
    - nvm install $NODE_VERSION
    #- mvn install -Ppackage-docker-image -rf :user-service -Dmaven.test.skip=true
  - stage: Build
    script:
    - mvn install -Ppackage-docker-image -rf :user-service -Dmaven.test.skip=true
    - mvn install -Ppackage-docker-image -Dmaven.test.skip=true -rf :recipe-service
    - mvn install -Ppackage-docker-image -rf :ingredient-service -Dmaven.test.skip=true
    - echo "$DOCKER_USERNAME"
    - echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin
    - docker tag unige/user-service pinfo2/user-service:latest
    - docker push pinfo2/user-service:latest
    - docker tag unige/ingredient-service pinfo2/ingredient-service:latest
    - docker push pinfo2/ingredient-service:latest
    - docker tag unige/recipe-service pinfo2/recipe-service:latest
    - docker push pinfo2/recipe-service:latest
    #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-2
    
    #- docker tag unige/api-gateway tropin98/api-gateway:latest
    #- docker tag unige/regulatory-service tropin98/regulatory-service:latest
    #- docker tag unige/valuation-service tropin98/valuation-service:latest
    #- docker tag unige/instrument-service tropin98/instrument-service:latest
    #- docker tag unige/counterparty-service tropin98/counterparty-service:latest
    #- docker push tropin98/api-gateway:latest
    #- docker push tropin98/regulatory-service:latest
    #- docker push tropin98/valuation-service:latest
    #- docker push tropin98/instrument-service:latest
    #- docker push tropin98/counterparty-service:latest
    #- mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-2 -Dsonar.organization=pinfo-2020
    #  -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=68db16192c9f0533a0926c86cf71c30b2331c97c
  #- stage: Build
    #script:
    #- cd web-ui
    #- pwd
    #- npm -v
    #- npm install
    #- npm update
    #- npm run-script build --prod
    #- docker build -t unige/web-ui .
    #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #- docker tag unige/web-ui tropin98/web-ui:latest
    #- docker push tropin98/web-ui:latest

addons:

  sonarcloud:

    organization: "pinfo-2020"

    token:
      secure: "iTNU0hd7cHZ7S4XrvkIy1Bm9iHBu2LF06LVFmmfoXH1ZMmEH01xxFJBEOpmqdRt/G4D5lXxFnlaTpnL6r7h85qim/8zTfQprM689wR3CSTjhk3EhWoYs6tyRcYrXGZK79UZWxrxvSn08ShwKXkIKUB9WZXSyBVTOea9pj3+4AryLLpCxPrsIcbh/fSBxX4UUUDuYDiYpzeQLWYq0WssVAWK0gXsVEfP90Xqpj2dJkddbZ9VkdTyX0cYTm0BtzdhdRCRWeCMxRjzMxStbnv38B1l6kivKO08hCZG9S6eyZiHKno016TLoELqsy39b1tAKht3h6+vvjMt9oCRty6Aw7CzXpwzRnZox+iZrb4e4WLQAZ2iVzzoGIzlZaJZBFeqmG2jkRT9qwM6kSumoj/o8wlrKH4hYd7BPM0jdNMT2s6w6lHZ8S6pz1aFQUirFHoi0nZbRVsuGP50AJox1ETu5amxIHPP+fmpVrMS2l/GaBwXshwglzGyBKvldKPDPdLndvP/BzTYE9hJv6Dnn2pC+k4xIkNxJp8lzhZv6SCJ1Pqn2FSpXZYrqGQAo6Wo0pVpHZxcKcP4uCQ/BP1kjY0+0mbfp2S2xr0UKMOhuD6yMuDDXqAI9mbsivitNhfmxbbKDo/7qIsBLx2aS3galk958W/ntmSCHysshbh6VB8dog/M="


script:

  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis

  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-2
