language: java

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules

jobs:
  include:
    - stage: Prepare
      script:
      - nvm install $NODE_VERSION
      - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage : Build
      script:
      - mvn install -Ppackage-docker-image  
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag unige/api-gateway stevehostettler/api-gateway:latest
      - docker tag unige/regulatory-service stevehostettler/regulatory-service:latest
      - docker tag unige/valuation-service stevehostettler/valuation-service:latest
      - docker tag unige/instrument-service stevehostettler/instrument-service:latest
      - docker tag unige/counterparty-service stevehostettler/counterparty-service:latest     
      - docker push stevehostettler/api-gateway:latest
      - docker push stevehostettler/regulatory-service:latest
      - docker push stevehostettler/valuation-service:latest
      - docker push stevehostettler/instrument-service:latest
      - docker push stevehostettler/counterparty-service:latest
      - mvn sonar:sonar -Dsonar.projectKey=hostettler_microservices -Dsonar.organization=hostettler-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=10de2947edc0e089a82360cb2d1aa97482fafc28     
    - stage : Build
      script:
      - cd web-ui
      - pwd
      - npm -v
      - npm install
      - npm update
      - npm run-script build --prod
      - docker build -t unige/web-ui .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin      
      - docker tag unige/web-ui stevehostettler/web-ui:latest      
      - docker push stevehostettler/web-ui:latest

addons:
  sonarcloud:
    organization: "pinfo-2020"
    token:
      secure: "cqm24L9BmfaHr5xVgD8JZxZexq0XLRiR0AvMwck5TtIFAl0sJFb47iwL7XKYoob3iIrtqOpp0h4hrD5VJBgWHnSQ+Ap0r4k749es5ptHV46H8PrsF3r9wR1PAUKm8Vo0YPt1t1J6KVIMwlRHqNUgiRlKwFD4VCeHqm8dmawYmNdj19hyz/eeaZ6zfIXvUxi/MdOki83VVVtJv3UtIkFPSTeuWRpy5O61KACAcdJeRgveA0bG25xkRvV1kHL6N2/tQlLWxuZ0cxQIxedYcl/kutkI4+bofnYX/LwgAlX2ha6bax30/uM4hZlwFhOgFx6QUZgZtoip7bg9G5d3s3jsCcSYMYFSxRCFEuROi+mLt6aCFZS13UvuXUYQOaHZexXF62J8WQqhcYTxrt8DTaVpQRI7aJ/dzLGChuYuMVe6F4Ngx/VqaWEyeqAgvEabsWvnT19L7ZYMHg+pOXrWbX/5kiOPOzSrnofyp4X/vEtSmAek/pV/U4mhF9d8hHexH7HD/huL2yapo/HZ1u4W6jMhtkbW2lfimJpUiQuzCS3mdcMDxpPRPbXk2DeZ+xxBndvZNkCDnvkoiwknqgT2eTKzilMX2u5z3y3ViB2n/b+e6gCbsoXYEctGtbnmaS3KzdUq5gII9sJ96o9ptEw68U29qoLfQbLKa+VpfEBj1JDUX0I="

addons:
  sonarcloud:
    organization: "pinfo-2020"
    token:
      secure: "" encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-2
