apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-counterparty-service
  labels:
    {{- include "microservices.labels" . | nindent 4 }}.counterparty-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microservices.selectorLabels" . | nindent 4 }}.counterparty-service
---    
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-instrument-service
  labels:
    {{- include "microservices.labels" . | nindent 4 }}.instrument-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microservices.selectorLabels" . | nindent 4 }}.instrument-service
---    
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-valuation-service
  labels:
    {{- include "microservices.labels" . | nindent 4 }}.valuation-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microservices.selectorLabels" . | nindent 4 }}.valuation-service
---    
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-regulatory-service
  labels:
    {{- include "microservices.labels" . | nindent 4 }}.regulatory-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microservices.selectorLabels" . | nindent 4 }}.regulatory-service     
