language: java

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

addons:
  sonarcloud:
    organization: "hostettler-github" # the key of the org you chose at step #3

cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules

jobs:
  include:
    - stage: Prepare
      script:
      - nvm install $NODE_VERSION
      - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage : Build
      script:
      - mvn install -Ppackage-docker-image  
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag unige/api-gateway stevehostettler/api-gateway:latest
      - docker tag unige/regulatory-service stevehostettler/regulatory-service:latest
      - docker tag unige/valuation-service stevehostettler/valuation-service:latest
      - docker tag unige/instrument-service stevehostettler/instrument-service:latest
      - docker tag unige/counterparty-service stevehostettler/counterparty-service:latest     
      - docker push stevehostettler/api-gateway:latest
      - docker push stevehostettler/regulatory-service:latest
      - docker push stevehostettler/valuation-service:latest
      - docker push stevehostettler/instrument-service:latest
      - docker push stevehostettler/counterparty-service:latest
      - mvn sonar:sonar -Dsonar.projectKey=hostettler_microservices -Dsonar.organization=hostettler-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=10de2947edc0e089a82360cb2d1aa97482fafc28     
    - stage : Build
      script:
      - cd web-ui
      - pwd
      - npm -v
      - npm install
      - npm update
      - npm run-script build --prod
      - docker build -t unige/web-ui .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin      
      - docker tag unige/web-ui stevehostettler/web-ui:latest      
      - docker push stevehostettler/web-ui:latest
